"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const csv_validate_js_1 = require("./csv-validate.js");
const mapping_js_1 = require("./mapping.js");
const router = (0, express_1.Router)();
router.get('/customers', mapping_js_1.getCustomers);
router.post('/customers/:Company/:ARDivisionNo-:CustomerNo', mapping_js_1.postCustomer);
router.get('/mapping/:Company/:ARDivisionNo-:CustomerNo', mapping_js_1.getMapping);
router.post('/mapping/:Company/:ARDivisionNo-:CustomerNo', mapping_js_1.postMapping);
router.delete('/mapping/:Company/:ARDivisionNo-:CustomerNo/:MapField/:CustomerValue', mapping_js_1.deleteMapping);
router.post('/upload', csv_validate_js_1.testCSVFile);
exports.default = router;
