"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const fba_1 = require("./seller-central/fba");
const router = (0, express_1.Router)();
router.post('/seller-central/fba/invoice/base', fba_1.postFBAInvoiceBaseData);
router.post('/seller-central/fba/invoice/charges', fba_1.postFBAInvoiceCharges);
router.post('/seller-central/fba/invoice/sales-order', fba_1.postFBAInvoiceSalesOrder);
router.post('/seller-central/fba/invoice', fba_1.postFBAInvoice);
router.post('/seller-central/fba/gl-account', fba_1.postGLAccount);
router.get('/seller-central/fba/item-map', fba_1.getItemMap);
router.post('/seller-central/fba/item-map', fba_1.postItemMap);
router.delete('/seller-central/fba/item-map/:sku', fba_1.deleteItemMap);
exports.default = router;
