import { Router } from 'express';
import { deleteFBAItem, deleteItemMap, getFBAItems, getItemMap, postFBAInvoice, postFBAInvoiceBaseData, postFBAInvoiceCharges, postFBAInvoiceSalesOrder, postFBAItem, postFBASettlement, postGLAccount, postItemMap } from './seller-central/fba/index.js';
import { deprecationNotice } from "chums-local-modules";
const router = Router();
router.post('/seller-central/fba/invoice/base.json', postFBAInvoiceBaseData);
router.post('/seller-central/fba/invoice/charges.json', postFBAInvoiceCharges);
router.post('/seller-central/fba/invoice/sales-order.json', postFBAInvoiceSalesOrder);
router.post('/seller-central/fba/invoice/settlement.json', postFBASettlement);
router.post('/seller-central/fba/invoice.json', postFBAInvoice);
router.post('/seller-central/fba/gl-account.json', postGLAccount);
router.get('/seller-central/fba/items.json', getFBAItems);
router.post('/seller-central/fba/items.json', postFBAItem);
router.delete('/seller-central/fba/items/:sku.json', deleteFBAItem);
router.get('/seller-central/fba/item-map.json', getItemMap);
router.post('/seller-central/fba/item-map.json', postItemMap);
router.delete('/seller-central/fba/item-map/:sku.json', deleteItemMap);
router.use(deprecationNotice);
router.post('/seller-central/fba/invoice/base', postFBAInvoiceBaseData);
router.post('/seller-central/fba/invoice/charges', postFBAInvoiceCharges);
router.post('/seller-central/fba/invoice/sales-order', postFBAInvoiceSalesOrder);
router.post('/seller-central/fba/invoice/settlement', postFBASettlement);
router.post('/seller-central/fba/invoice', postFBAInvoice);
router.post('/seller-central/fba/gl-account', postGLAccount);
router.get('/seller-central/fba/item-map', getItemMap);
router.post('/seller-central/fba/item-map', postItemMap);
router.delete('/seller-central/fba/item-map/:sku', deleteItemMap);
export default router;
